name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync

      - name: Run Pytest
        run: uv run pytest tests -s

      - name: Build
        if: github.event_name == 'workflow_dispatch'
        run: uv run pyinstaller main.spec --clean --noconfirm --distpath .

      - name: Package
        if: github.event_name == 'workflow_dispatch'
        run: |
            mkdir output\resource
            xcopy src\resource output\resource /s /e /v /q /y
            mkdir output\resource_ja
            xcopy src\resource_ja output\resource_ja /s /e /v /q /y
            Compress-Archive -Path output\* -DestinationPath "OnmyojiDesktopAssistant-debug.zip"

      - name: Upload build
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v7
        with:
          name: OnmyojiDesktopAssistant
          path: OnmyojiDesktopAssistant-debug.zip
          retention-days: 7
