name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'AquamarineCyan' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: win
            arch: x64
            filename: 'OnmyojiDesktopAssistant-*.zip'

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ matrix.filename }}
          mirrorchyan_rid: OnmyojiDesktopAssistant
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: AquamarineCyan
          repo: OnmyojiDesktopAssistant
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
