name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Install dependencies
        run: uv sync

      - name: Run Pytest
        run: uv run pytest tests -s

      - name: Build
        run: uv run pyinstaller main.spec --clean --noconfirm --distpath .

      - name: Package
        run: |
            mkdir output\resource
            xcopy src\resource output\resource /s /e /v /q /y
            mkdir output\resource_ja
            xcopy src\resource_ja output\resource_ja /s /e /v /q /y
            
            $version = "${{ github.ref_name }}" -replace "^v", ""
            Compress-Archive -Path output\* -DestinationPath "OnmyojiDesktopAssistant-$version.zip"

      - name: Upload build
        uses: actions/upload-artifact@v7
        with:
          name: OnmyojiDesktopAssistant
          path: OnmyojiDesktopAssistant-*.zip
          retention-days: 7

  release:
    name: Release
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Check files
        shell: pwsh
        run: |
          Get-ChildItem -Recurse

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: OnmyojiDesktopAssistant-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger MirrorChyanUploading
        shell: bash
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release.yml -f tag=${{ github.ref_name }}
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note.yml -f tag=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

